server:
  port: 8080
redis:
  host: localhost
  port: 6379
logger:
  #silent,error,warn,info,debug
  show_sql: true
  level: debug
database:
  # 缓存类型：sqlite,mysql
  type: sqlite
  sqlite:
    file: file::memory:?cache=shared
#  mysql:
#    host: localhost
#    port: 3306
#    name: notebook
#    username: root
#    password: 123456

cache:
  # 缓存类型：memory,redis
  type: redis
  expiration: -1s