name: go tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  go-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: ./
        if: ${{ env.ACT }}
      - uses: actions/checkout@master
        if: ${{ !env.ACT }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - run: go test -v -race
        env:
          GIN_MODE: test
          redis.host: localhost
          redis.port: 6379
          cache.type: memory
          database.type: mysql
          database.sqlite.file: test.db
